/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TikvConnParams {
  tlsclusterenabled: boolean
  sslcacerti: string
  sslclientcerti: string
  sslclientkeycerti: string
  host: string
}
export interface BatchResponse {
  keys: Array<string>
  values?: Array<string>
}
export function initClient(tikvConnParam?: TikvConnParams | undefined | null): Promise<string>
export function startLogger(): void
export function getSingleRecord(key: string, projectName?: string | undefined | null): Promise<string>
export function addSingleRecord(
  key: string,
  value: string,
  oldValue?: string | undefined | null,
  projectName?: string | undefined | null,
): Promise<string>
